# ??rabbitmq???????
spring:
  rabbitmq:
    host: 172.26.41.194
    port: 5672
    username: admin
    password: admin
    virtual-host: /hzero
    #NONE???????????????
    #CORRELATED??????????????????????1??
    #SIMPLE???????????????CORRELATED???????????????????????rabbitTemplate??waitForConfirms?waitForConfirmsOrDie????broker???????????????????????????????waitForConfirmsOrDie??????false????channel????????????broker;
    publisher-confirm-type: correlated
    # ??????
    publisher-returns: true
    template:
      mandatory: true

